### PR TITLE
Fixes for misc problems found when using generating file for SCB:s database

### PR DESCRIPTION
**Pull request by likp**
Added identifer for the Catalog
Removed phone from contacts
Fixed misc casing problems

### CODE REVIEW

**Review by KentMossback — APPROVED** [review]
Will out commented code be implemented in the future?

**Comment by likp** [comment]
@KentMossback, they might come back when we know that we can assert that the phone numbers are in the correct format.

**Review by KentMossback — APPROVED** [review]
Looks good!

**Review by KentMossback — APPROVED** [review]
Ok

**Pull request merged**
